---
abstract: 'Classes for reading and writing directed graphs'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6905, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graph-ReadWrite
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  File::Compare: 0
  Graph: 0.5
  IO::File: 0
  Parse::Yapp::Driver: 0
  XML::Parser: 0
  XML::Writer: 0
  parent: 0
resources:
  repository: https://github.com/neilbowers/Graph-ReadWrite
version: 2.04
